#!/usr/bin/env python3
"""Write paper/ieee/resubmission-checklist.md from the package that
scripts/pack-ieee-submission.sh just built, so the checklist can never
describe an older build: file sizes, SHA-256 digests and page counts are
read from the files, and the abstract to paste is taken from the LaTeX
source with its macros expanded (text copied from the PDF loses the hyphen
of a word broken across lines).

Usage: gen-resubmission-checklist.py [SUBMISSION_DIR]
"""
import hashlib
import os
import re
import subprocess
import sys

SUB = sys.argv[1] if len(sys.argv) > 1 else "paper/ieee/submission"
OUT = "paper/ieee/resubmission-checklist.md"
ABSTRACT_LIMIT = 250


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def pages(path):
    info = subprocess.run(["pdfinfo", path], capture_output=True, text=True, check=True).stdout
    return int(re.search(r"Pages:\s+(\d+)", info).group(1))


def size(path):
    return f"{os.path.getsize(path):,}"


def abstract():
    macros = dict(re.findall(r"\\newcommand\{\\(\w+)\}\{(.*)\}", open("paper/macros.tex").read()))
    src = open("paper/ieee/main.tex").read()
    text = re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", src, re.S).group(1)
    text = text.replace("\\sivm{}", "sIVM")
    names = sorted(macros, key=len, reverse=True)
    text = re.sub(
        # A control space after a macro may be a backslash before a line end.
        r"\\(" + "|".join(map(re.escape, names)) + r")(\\\s|\{\}|(?=[^A-Za-z]))",
        lambda m: macros[m.group(1)] + (" " if m.group(2) else ""),
        text,
    )
    text = text.replace("{,}", ",").replace("\\%", "%").replace("\\$", "$").replace("\\ ", " ")
    text = re.sub(r"\s+", " ", text).strip()
    if "\\" in text or "{" in text:
        sys.exit(f"abstract still carries TeX after expansion: {text}")
    return text


def git(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True).stdout.strip()


files = {name: os.path.join(SUB, name) for name in ["manuscript.pdf", "source.zip", "highlighted.pdf", "response-to-reviewers.docx", "response-to-reviewers.pdf", "cover-letter.pdf"]}
for name, path in files.items():
    if not os.path.exists(path):
        sys.exit(f"{path} is missing; run pnpm pack:paper:ieee first")

text = abstract()
words = len(text.split())
if words > ABSTRACT_LIMIT:
    sys.exit(f"the abstract has {words} words; the limit is {ABSTRACT_LIMIT}")
head = git("rev-parse", "--short", "HEAD")
dirty = bool(git("status", "--porcelain", "--untracked-files=no"))
state = f"commit `{head}`" + (" plus uncommitted changes (commit, then pack again before uploading)" if dirty else "")
keywords = re.search(r"\\begin\{keywords\}(.*?)\\end\{keywords\}", open("paper/ieee/main.tex").read(), re.S).group(1)
keywords = re.sub(r"\s+", " ", keywords).strip().rstrip(".")

row = lambda slot, desc, name: f"| {slot} | {desc} | {size(files[name])} | `{sha256(files[name])}` |"
lines = [
    "# IEEE Access resubmission checklist: Access-2026-41149",
    "",
    f"Generated by `scripts/gen-resubmission-checklist.py` from the package built at {state}. Regenerate with `pnpm pack:paper:ieee`; the outputs are in `paper/ieee/submission/`, which is gitignored. The digests below are of that build, so upload the files from the same run.",
    "",
    '## 1. Files and where they go (IEEE Author Portal, "Start Resubmission" on Access-2026-41149)',
    "",
    "| Portal slot | File | Size | SHA-256 |",
    "| --- | --- | ---: | --- |",
    row("Main Manuscript (clean): PDF", f"`manuscript.pdf` ({pages(files['manuscript.pdf'])} pages)", "manuscript.pdf"),
    row("Main Manuscript (clean): LaTeX source", "`source.zip` (flat: main.tex, body, tables, macros, refs.bib, main.bbl, main.pdf, class and fonts)", "source.zip"),
    row("Highlighted PDF (all changes marked)", f"`highlighted.pdf` ({pages(files['highlighted.pdf'])} pages; blue = added or changed, deletions omitted, changed numbers marked, reference list compared entry by entry)", "highlighted.pdf"),
    row("Author's Response Files (point-by-point)", f"`response-to-reviewers.docx` ({pages(files['response-to-reviewers.pdf'])} pages as PDF; the `.pdf` twin is the same text if the portal prefers PDF)", "response-to-reviewers.docx"),
    row("Cover letter", f"`cover-letter.pdf` ({pages(files['cover-letter.pdf'])} page), or paste its text into the cover-letter field", "cover-letter.pdf"),
    "",
    "Not needed: the byline-change form (single author, unchanged). The portal's resubmission checklist template: answer that every reviewer comment is addressed in the response file, that the highlighted copy marks every change, and that the byline is unchanged.",
    "",
    "## 2. Form fields (unchanged from the first submission unless noted)",
    "",
    "| Field | Answer |",
    "| --- | --- |",
    "| Manuscript ID | Access-2026-41149 (resubmission of the 29 September 2026 decision) |",
    "| Article type | Regular Manuscript / Research Article |",
    "| Title | Reuse, but Verify: Certified Maintenance of Table Cells Computed by Large Language Models under Prompt Edits |",
    f"| Abstract (paste; {words} words) | see below |",
    f"| Index terms | {keywords} |",
    "| Corresponding author | Arjun Lohan, lohan@usc.edu, ORCID 0009-0003-3605-1221, University of Southern California, Los Angeles, CA 90089 USA |",
    "| Funding / conflicts | None / None |",
    "| Preprint | Yes: Zenodo, doi:10.5281/zenodo.21833641 (declared in the cover letter and named in the manuscript's Availability section; expect high iThenticate similarity to it and to the first submission) |",
    "| Under review elsewhere | No |",
    "| Supplementary files | None (code, labels, artifacts are public in the repository named in the Availability section) |",
    "| License at acceptance | CC BY; APC personal |",
    "",
    "### Abstract text to paste",
    "",
    text,
    "",
    "## 3. Before you press submit",
    "",
    "- Open `highlighted.pdf` once and confirm blue text appears on page 1 (the abstract) and in the reference list.",
    "- The response document's opening letter names the three file designations; keep them consistent with the slots you use.",
    "- Do not upload the `.partial.json` checkpoints or anything from `paper/ieee/submission/diff/`.",
    "- The author biography has no photograph (optional at every stage); add one only if you want it printed.",
    "",
    "## 4. After submission",
    "",
    "- Record the new submission timestamp and any new manuscript ID in `tasks/todo.md`.",
    "- On acceptance: final files, graphical abstract (Figure 1 export, 660x295 JPG under 45 KB, caption under 60 words), Zenodo record updated with the IEEE citation and DOI.",
    "",
]
open(OUT, "w").write("\n".join(lines))
print(f"checklist: {OUT} (abstract {words} words; {state})")
